# Project: cleanning - [candy data]
### this notebook is for educational purpose . in this notebook we will do some cleanning

## Table of Contents
<ul>
<li><a href="#intro">Introduction</a></li>
<li><a href="#wrangling">wrangling</a></li>
  
</ul>

<a id='intro'></a>
## Introduction

### Dataset Description

> i will go through candy data 2017 , this data has :
- Internal_ID
- Q1-Going Out?: Are you actually going trick or treating yourself? "has values `Yes or No`"
- Q2-Gender: It has four different options, `Femal ,Male ,Other ,I'd rather not say`
- Q3-Age: Numerical field
- Q4-Country: Text Field, but users have written their own version of the names. Example, for America, there are entries such as USA, us, US, America so we should consider that while cleanning
- Q5-State/Province: Text Field, but users have written their own version of the names. Same as the country data.
- Q6-Joy Or Despair: All kinds of chocolate bars are the questions with three distinct options to choose from (Joy, Meh, Despair).
- Q7-Joy Other: Text Field to write items not included above that give you JOY. Lots of missing values.
- Q8-Despair Other: Text Field ti write items not included above that give you DESPAIR. Lots of missing values.
- Q9-Other Comments: Text Field. Lots of missing values.
- Q10-Dress: Binary field. Missing values present
- Unnamed: 113
- Q11-Day: Binary Answer Field. Missing values present

# 1- import packages and load data

In [22]:
import pandas as pd
import numpy as np

data = pd.read_excel('/content/candyhierarchy2017.xlsx')

data.head()

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"

<a id='wrangling'></a>
## Data Wrangling



### General Properties

# 2- show some general properties for the data

In [23]:
print(data.info())
print('********************************************')
print(data.isnull().sum().sort_values(ascending=False).to_string())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2460 entries, 0 to 2459
Columns: 120 entries, Internal ID to Click Coordinates (x, y)
dtypes: float64(4), int64(1), object(115)
memory usage: 2.3+ MB
None
********************************************
Unnamed: 113                                                                              2451
Q12: MEDIA [Yahoo]                                                                        2393
Q12: MEDIA [Daily Dish]                                                                   2375
Q12: MEDIA [ESPN]                                                                         2361
Q9: OTHER COMMENTS                                                                        2074
Q8: DESPAIR OTHER                                                                         1743
Q7: JOY OTHER                                                                             1549
Q12: MEDIA [Science]                                                                      1098
Q6 | JoyJoy (Mit Iodine!)                                                                 1026
Q6 | Maynards                                                                             1024
Q6 | Reggie Jackson Bar                                                                   1014
Q6 | Bonkers (the board game)                                                             1006
Q6 | Sweetums (a friend to diabetes)                                                      1002
Q6 | Bonkers (the candy)                                                                   992
Q6 | Black Jacks                                                                           958
Q6 | Chick-o-Sticks (we don’t know what that is)                                           946
Q6 | Kinder Happy Hippo                                                                    945
Q6 | Abstained from M&M'ing.                                                               942
Q6 | Senior Mints                                                                          942
Q6 | Take 5                                                                                917
Q6 | Smarties (Commonwealth)                                                               901
Q6 | Spotted Dick                                                                          882
Q6 | Goo Goo Clusters                                                                      879
Click Coordinates (x, y)                                                                   855
Q6 | Coffee Crisp                                                                          853
Q6 | Fuzzy Peaches                                                                         823
Q6 | Whatchamacallit Bars                                                                  823
Q6 | Now'n'Laters                                                                          817
Q6 | Independent M&M's                                                                     813
Q6 | Mint Juleps                                                                           811
Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein                792
Q6 | Vicodin                                                                               789
Q6 | Sandwich-sized bags filled with BooBerry Crunch                                       776
Q6 | Mint Kisses                                                                           776
Q6 | Bottle Caps                                                                           765
Q6 | Green Party M&M's                                                                     764
Q6 | White Bread                                                                           757
Q6 | Real Housewives of Orange County Season 9 Blue-Ray                                    753
Q6 | Caramellos                                                                            752
Q6 | Whole Wheat anything                                                                  747
Q6 | 100 Grand Bar                                                                         747
Q6 | Kale smoothie                                                                         744
Q10: DRESS                                                                                 744
Q6 | Necco Wafers                                                                          744
Q6 | Chardonnay                                                                            743
Q6 | Mr. Goodbar                                                                           740
Q6 | Sourpatch Kids (i.e. abominations of nature)                                          738
Q6 | LaffyTaffy                                                                            736
Q6 | Those odd marshmallow circus peanut things                                            736
Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)     734
Q6 | Good N' Plenty                                                                        734
Q6 | Generic Brand Acetaminophen                                                           731
Q6 | LemonHeads                                                                            730
Q6 | Dots                                                                                  729
Q6 | Red M&M's                                                                             729
Q6 | Mike and Ike                                                                          729
Q6 | Blue M&M's                                                                            727
Q6 | Mars                                                                                  725
Q6 | Smarties (American)                                                                   725
Q11: DAY                                                                                   725
Q6 | Minibags of chips                                                                     724
Q6 | Nerds                                                                                 723
Q6 | Pixy Stix                                                                             722
Q6 | Lindt Truffle                                                                         718
Q6 | Gum from baseball cards                                                               716
Q6 | Swedish Fish                                                                          715
Q6 | Tic Tacs                                                                              714
Q6 | Rolos                                                                                 714
Q6 | Hugs (actual physical hugs)                                                           713
Q6 | Heath Bar                                                                             712
Q6 | Chiclets                                                                              711
Q6 | Peeps                                                                                 710
Q6 | Pencils                                                                               709
Q6 | Sweet Tarts                                                                           708
Q6 | Three Musketeers                                                                      708
Q6 | Trail Mix                                                                             708
Q6 | Skittles                                                                              706
Q6 | Broken glow stick                                                                     706
Q6 | Tolberone something or other                                                          706
Q6 | York Peppermint Patties                                                               705
Q6 | Creepy Religious comics/Chick Tracts                                                  704
Q6 | Dove Bars                                                                             702
Q6 | Junior Mints                                                                          698
Q6 | Nestle Crunch                                                                         698
Q6 | Gummy Bears straight up                                                               697
Q6 | Glow sticks                                                                           697
Q6 | Jolly Ranchers (good flavor)                                                          695
Q6 | Hard Candy                                                                            695
Q6 | Healthy Fruit                                                                         694
Q6 | Jolly Rancher (bad flavor)                                                            694
Q6 | Milk Duds                                                                             693
Q6 | Starburst                                                                             693
Q6 | Dental paraphenalia                                                                   692
Q6 | Lollipops                                                                             691
Q6 | Candy that is clearly just the stuff given out for free at restaurants                691
Q6 | Reese's Pieces                                                                        691
Q6 | Twix                                                                                  690
Q6 | Snickers                                                                              690
Q6 | Milky Way                                                                             688
Q6 | Box'o'Raisins                                                                         688
Q6 | Licorice (not black)                                                                  686
Q6 | Licorice (yes black)                                                                  685
Q6 | Cadbury Creme Eggs                                                                    683
Q6 | Butterfinger                                                                          682
Q6 | Cash, or other forms of legal tender                                                  680
Q6 | Reese’s Peanut Butter Cups                                                            679
Q6 | Candy Corn                                                                            678
Q6 | Hershey's Kisses                                                                      678
Q6 | Regular M&Ms                                                                          675
Q6 | Kit Kat                                                                               674
Q6 | Hershey's Dark Chocolate                                                              673
Q6 | Any full-sized candy bar                                                              672
Q6 | Hershey’s Milk Chocolate                                                              672
Q6 | Peanut M&M’s                                                                          671
Q1: GOING OUT?                                                                             110
Q5: STATE, PROVINCE, COUNTY, ETC                                                           100
Q3: AGE                                                                                     84
Q4: COUNTRY                                                                                 64
Q2: GENDER                                                                                  41
Internal ID                                                                                  0

# 3- write summary about what you get form the above functions
> #### tips : this summary can be about : if there is any missing values , if there a wrong data type , if there a wrong range of values , ....

In [24]:
#The dataset contains 2,460 rows and 120 columns.
#There are many missing values across the dataset. Most survey question columns have fewer than 2,460 non-null values
#and some columns have a very high percentage of missing data
#Q9: OTHER COMMENTS has only 386 non-null values.    Unnamed: 113 has only 9 non-null values.    Q12: MEDIA [Yahoo] has only 67 non-null values
#some columns such as Age are also stored as object, which may require conversion to a numeric data type
#dataset also contain inconsistent categorical values (for example, country names with different capitalization such as "USA", "usa", and "us")

# cleaning

### 4- drop all the useless columns and  rows with too much NaN ,
> tip : useless columns can be like `Internal ID`and can be also columns with too much NaN
- rename columns for easy access

### make media column and drop all 4 media columns

In [25]:
media_cols = ['Q12: MEDIA [Yahoo]','Q12: MEDIA [Daily Dish]','Q12: MEDIA [ESPN]','Q12: MEDIA [Science]']

data['Media'] = data[media_cols].idxmax(axis = 1).str.extract(r'\[(.*?)\]')
data = data.drop(columns=media_cols)

data['Media'] = data['Media'].fillna("Unknown")
data['Media'].value_counts(dropna = False)

/tmp/ipykernel_858/4084153103.py:3: FutureWarning: The behavior of DataFrame.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  data['Media'] = data[media_cols].idxmax(axis = 1).str.extract(r'\[(.*?)\]')

Media
Science       1362
Unknown        847
ESPN            99
Daily Dish      85
Yahoo           67
Name: count, dtype: int64

### drop the columns that are useless

In [26]:
data = data.drop(['Unnamed: 113','Q9: OTHER COMMENTS','Q8: DESPAIR OTHER','Q7: JOY OTHER'], axis = 1)
data['Internal ID'] = data['Internal ID'].astype('string')
data

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,"Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein",Q6 | Vicodin,Q6 | Whatchamacallit Bars,Q6 | White Bread,Q6 | Whole Wheat anything,Q6 | York Peppermint Patties,Q10: DRESS,Q11: DAY,"Click Coordinates (x, y)",Media
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,DESPAIR,DESPAIR,DESPAIR,DESPAIR,DESPAIR,DESPAIR,White and gold,Sunday,"(84, 25)",Science
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,DESPAIR,JOY,JOY,DESPAIR,DESPAIR,DESPAIR,White and gold,Sunday,"(75, 23)",Science
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,MEH,JOY,JOY,DESPAIR,DESPAIR,JOY,White and gold,Friday,"(70, 10)",Science
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,90314359,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,...,MEH,JOY,DESPAIR,MEH,DESPAIR,MEH,White and gold,Friday,NaN,Unknown
2456,90314580,No,Female,33,USA,New York,MEH,DESPAIR,JOY,NaN,...,NaN,NaN,JOY,DESPAIR,MEH,JOY,Blue and black,Friday,"(70, 26)",Science
2457,90314634,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,...,MEH,JOY,MEH,DESPAIR,DESPAIR,MEH,Blue and black,Friday,"(67, 35)",Science
2458,90314658,No,Male,58,Usa,North Carolina,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown
2459,90314802,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,...,DESPAIR,JOY,DESPAIR,MEH,DESPAIR,JOY,White and gold,Sunday,"(19, 26)",Daily Dish

### drop all the rows that has no information

In [27]:
data = data[data.isnull().sum(axis=1) <= 100].reset_index(drop=True)
data

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,"Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein",Q6 | Vicodin,Q6 | Whatchamacallit Bars,Q6 | White Bread,Q6 | Whole Wheat anything,Q6 | York Peppermint Patties,Q10: DRESS,Q11: DAY,"Click Coordinates (x, y)",Media
0,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,DESPAIR,DESPAIR,DESPAIR,DESPAIR,DESPAIR,DESPAIR,White and gold,Sunday,"(84, 25)",Science
1,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,DESPAIR,JOY,JOY,DESPAIR,DESPAIR,DESPAIR,White and gold,Sunday,"(75, 23)",Science
2,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,MEH,JOY,JOY,DESPAIR,DESPAIR,JOY,White and gold,Friday,"(70, 10)",Science
3,90272852,No,Male,NaN,NaN,NaN,JOY,DESPAIR,JOY,NaN,...,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,NaN,NaN,"(75, 23)",Science
4,90272854,No,Male,33,canada,ontario,JOY,DESPAIR,JOY,DESPAIR,...,JOY,MEH,DESPAIR,DESPAIR,DESPAIR,DESPAIR,Blue and black,Friday,"(55, 5)",Science
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1795,90314022,No,Female,26,USA,Michigan,JOY,MEH,JOY,DESPAIR,...,MEH,MEH,JOY,MEH,MEH,JOY,White and gold,Friday,"(68, 39)",Science
1796,90314359,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,...,MEH,JOY,DESPAIR,MEH,DESPAIR,MEH,White and gold,Friday,NaN,Unknown
1797,90314580,No,Female,33,USA,New York,MEH,DESPAIR,JOY,NaN,...,NaN,NaN,JOY,DESPAIR,MEH,JOY,Blue and black,Friday,"(70, 26)",Science
1798,90314634,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,...,MEH,JOY,MEH,DESPAIR,DESPAIR,MEH,Blue and black,Friday,"(67, 35)",Science
1799,90314802,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,...,DESPAIR,JOY,DESPAIR,MEH,DESPAIR,JOY,White and gold,Sunday,"(19, 26)",Daily Dish

### 5 - clean `going out` column
> tip : you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [28]:
print(data['Q1: GOING OUT?'].value_counts(dropna=False))

mode = data['Q1: GOING OUT?'].mode()[0]

data['Q1: GOING OUT?'] = data['Q1: GOING OUT?'].fillna(mode)

print("**************************************")

data['Q1: GOING OUT?'].value_counts(dropna=False)

Q1: GOING OUT?
No     1499
Yes     238
NaN      63
Name: count, dtype: int64
**************************************

Q1: GOING OUT?
No     1562
Yes     238
Name: count, dtype: int64

### 6 - clean ` gender` column
> tip : you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [29]:
print(data['Q2: GENDER'].value_counts(dropna = False).sort_values(ascending=False))

mode = data['Q2: GENDER'].mode()[0]

data['Q2: GENDER'] = data['Q2: GENDER'].replace(np.nan, "I'd rather not say")

data['Q2: GENDER'].value_counts().sort_values(ascending=False)

Q2: GENDER
Male                  1085
Female                 618
I'd rather not say      61
Other                   26
NaN                     10
Name: count, dtype: int64

Q2: GENDER
Male                  1085
Female                 618
I'd rather not say      71
Other                   26
Name: count, dtype: int64

### 7 - clean ` age` column
> tip : note the type of age column , and NaN values
 - try to use `to_numeric`
 - tip : you should choose which best value to put in place of these NaNs ( mean, median, ....etc)

In [30]:
print(data['Q3: AGE'].value_counts(dropna = False))

data = data.drop(data.loc[data['Q3: AGE'].isin(['I can remember when Java was a cool new language','MY NAME JEFF'])].index)

data['Q3: AGE'] = data['Q3: AGE'].replace(['old','OLD','ancient','Over 50',"older than dirt"], '55')
data['Q3: AGE'] = data['Q3: AGE'].replace(['46 Halloweens.','old enough',"Old enough",'24-50','Enough',"Many","45-55"], '46')
data['Q3: AGE'] = data['Q3: AGE'].replace('60+', '60')
data['Q3: AGE'] = data['Q3: AGE'].replace('sixty-nine', '69')
data['Q3: AGE'] = data['Q3: AGE'].replace(['59 on the day after Halloween','5u'], '59')
data["Q3: AGE"] = data["Q3: AGE"].replace(["See question 2",102,100,1000,"?","no","hahahahaha",'your mom'], np.nan)

data["Q3: AGE"] = pd.to_numeric(data["Q3: AGE"])
data.loc[(data['Q3: AGE'] < 10) | (data['Q3: AGE'] > 100) , 'Q3: AGE'] = np.nan
mean_Age = data["Q3: AGE"].mean()
data["Q3: AGE"] = data["Q3: AGE"].replace(np.nan, mean_Age)
print("*****************************************")
data["Q3: AGE"] = data["Q3: AGE"].round().astype(int)
data['Q3: AGE'].value_counts(dropna = False)

Q3: AGE
40                                                  66
37                                                  66
43                                                  64
44                                                  62
34                                                  61
                                                    ..
OLD                                                  1
MY NAME JEFF                                         1
4                                                    1
old enough                                           1
I can remember when Java was a cool new language     1
Name: count, Length: 100, dtype: int64
*****************************************

Q3: AGE
43    115
40     66
37     66
44     62
34     61
     ...
14      2
74      1
88      1
99      1
77      1
Name: count, Length: 71, dtype: int64

### 8 - clean ` country` column
> tip : note that country column has country names with different writing ways
  - use fuzzywuzzy to deal with this problem
  - you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [31]:
!pip install fuzzywuzzy
!pip install pycountry
import fuzzywuzzy
from fuzzywuzzy import fuzz, process
import pycountry

data["Q4: COUNTRY"] = data["Q4: COUNTRY"].apply(lambda x: "Unknown" if isinstance(x, int) else x)

data["Q4: COUNTRY"] = data["Q4: COUNTRY"].fillna("Unknown")
data["Q4: COUNTRY"].unique()
countries = [c.name for c in pycountry.countries]
abr_dic = {
    'i pretend to be from canada, but i am really from the united states': "United States",
    "murica": "United States",
    'the united states of america': "United States",
    "unknown": "Unknown",
    "uae": "United Arab Emirates",
    "us": "United States","usa": "United States","ussa": "United States","u.s.": "United States","u.s.a.": "United States",
    "u s": "United States","u s a": "United States","usausausa": "United States",
    "america": "United States",
    'murrica': "United States",'murrika': "United States","'merica": "United States",
    'us of a':"United States",
    "ahemamerca": "United States",
    "usa? hard to tell anymore": "United States",'trumpistan': "United States",
    "usa usa usa!!!!":"United States",
    'pittsburgh':"United States",'new york':"United States",'new jersey':"United States",'north carolina':"United States",
    'california':"United States",'alaska':"United States",
    "uk": "United Kingdom",
    "u.k.": "United Kingdom",
    "britain": "United Kingdom",
}

def clean_country(name, choices=countries, threshold=60):
    raw = str(name).strip()
    key = (raw.lower().replace(".", "")).strip()

    if key in abr_dic:
        return abr_dic[key]

    match, score = process.extractOne(raw, choices, scorer=fuzz.token_sort_ratio)

    if score >= threshold:
        return match
    else:
        return "Unknown"

data['Q4: COUNTRY'] = data['Q4: COUNTRY'].apply(clean_country)
data['Q4: COUNTRY'].value_counts(dropna = False)

Requirement already satisfied: fuzzywuzzy in /usr/local/lib/python3.12/dist-packages (0.18.0)
Requirement already satisfied: pycountry in /usr/local/lib/python3.12/dist-packages (26.2.16)

Q4: COUNTRY
United States           1547
Canada                   161
Unknown                   26
United Kingdom            18
Germany                    7
Netherlands                4
Ireland                    3
France                     3
Japan                      3
Poland                     3
Mexico                     2
Greenland                  2
Switzerland                2
Australia                  2
Denmark                    2
United Arab Emirates       1
Greece                     1
Costa Rica                 1
Iceland                    1
Kenya                      1
South Africa               1
Albania                    1
American Samoa             1
Singapore                  1
Thailand                   1
China                      1
Spain                      1
Armenia                    1
Name: count, dtype: int64

### 9 - clean ` area` column
> tip : area column has the same problem as country columns , but looking at all it's unique values may give us another way to deal with it rather than try to fix it

In [32]:
def replace_match_in_column(df,column,string_to_match,min_ratio = 50):
  strings = df[column].unique()
  matches = fuzzywuzzy.process.extract(string_to_match, strings, limit = 10,scorer= fuzzywuzzy.fuzz.token_sort_ratio)
  close_matches = [matches[0] for matches in matches if matches[1] > min_ratio]
  print(close_matches)
  rows_with_matches = df[column].isin(close_matches)
  df.loc[rows_with_matches,column] = string_to_match


data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace(['CA', 'CA, Alameda','ca','Ca'],'California')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace(['WA','Wa','wa'],'Washington')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace(['NY','ny'],'New York')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace('PA','Pennsylvania')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace(['TX', 'tx', 'Tx.', 'Tx'],'Pennsylvania')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace(['ill','IL'],'Illinois')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace(['or','OR','Or'],'Oregon')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace(['ON','On'],'Ontario')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace(['BC','Bc','bc'],'British Columbia')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace(['MA','ma'],'Massachusetts')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace(['VA','va'],'Virginia')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace('NC','Carolina')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace(['MN','Mn','mn'],'Minnesota')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace('FL','Florida')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace('GA','Georgia')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace('MO','Missouri')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace('CO','Colorado')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace('NJ','New Jersey')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace('MD','Maryland')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace('NJ','New Jersey')
data['Q5: STATE, PROVINCE, COUNTY, ETC'] = data['Q5: STATE, PROVINCE, COUNTY, ETC'].replace('mi','Michigan')

def data_clean_area(df, area, ratio = 60):
  data.loc[data['Q5: STATE, PROVINCE, COUNTY, ETC'].str.contains(area, case = False, na = False),'Q5: STATE, PROVINCE, COUNTY, ETC'] = area
  replace_match_in_column(data,'Q5: STATE, PROVINCE, COUNTY, ETC', area, ratio)

data_clean_area(data, 'California')
data_clean_area(data, 'New York')
data_clean_area(data, 'Washington',65)
data_clean_area(data, 'Texas')
data_clean_area(data, 'Illinois')
data_clean_area(data, 'Pennsylvania')
data_clean_area(data, 'Oregon')
data_clean_area(data, 'Ontario')
data_clean_area(data, 'Ohio',60)
data_clean_area(data, 'Virginia',70)
data_clean_area(data, 'Alberta')
data_clean_area(data, 'Massachusetts',60)
data_clean_area(data, 'Michigan',75)
data_clean_area(data, 'Wisconsin')
data_clean_area(data, 'Florida')
data_clean_area(data, 'Colorado',75)
data_clean_area(data, 'Carolina',75)
data_clean_area(data, 'Indiana',75)
data_clean_area(data, 'Missouri',75)
data_clean_area(data, 'British Columbia')
data_clean_area(data, 'Minnesota')
data_clean_area(data, 'Michigan',75)
data_clean_area(data, 'New Jersey')
data_clean_area(data, 'Maryland',70)

data = data.replace(np.nan, 'Unknown')
print(data['Q5: STATE, PROVINCE, COUNTY, ETC'].value_counts(dropna=False).head(20))

['California', 'cailifornia', 'califormia', 'Califor', 'Carolina', 'calif']
['New York']
['Washington', 'Washingto']
['Texas']
['Illinois']
['Pennsylvania']
['Oregon']
['Ontario']
['Ohio', 'HI', 'hi', 'OH']
['Virginia']
['Alberta']
['Massachusetts', 'Massachussets ']
['Michigan', 'Michigin']
['Wisconsin']
['Florida']
['Colorado']
['Carolina']
['Indiana']
['Missouri', 'Missoure']
['British Columbia']
['Minnesota']
['Michigan']
['New Jersey']
['Maryland']
Q5: STATE, PROVINCE, COUNTY, ETC
California          260
Washington           98
New York             79
Pennsylvania         77
Illinois             74
Oregon               65
Ontario              64
Massachusetts        63
Virginia             53
Texas                52
Ohio                 48
British Columbia     45
Minnesota            45
Unknown              41
Florida              34
Colorado             33
Michigan             32
Georgia              28
Alberta              27
Missouri             25
Name: count, dtype: int64

### 10 - clean ` Q6` columns
>- tip : Q6 has all kinds of chocolate bars and questions with three distinct options to choose from (Joy, Meh, Despair).
- so all the column that has Q6 is a candy name , so you should go through all these column and you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

### make another dataset for the candies and keep the ID of the person so that we can data modeling this dataset with data dataset

In [33]:
candy_cols = [col for col in data.columns if col.startswith('Q6 | ')]

candy_data = data[['Internal ID'] + candy_cols]

candy_data = data.melt(
    id_vars='Internal ID',
    value_vars = candy_cols,
    var_name='Candy',
    value_name='Rating'
)

candy_data['Candy'] = candy_data['Candy'].str.replace('Q6 | ', '', regex=False)

candy_data = candy_data.dropna(subset=['Rating'])

candy_data = candy_data.reset_index(drop=True)

data = data.drop(columns = candy_cols)

candy_data[candy_data['Internal ID'] == '90272821']

       Internal ID                                              Candy   Rating
0         90272821                                      100 Grand Bar      MEH
1798      90272821  Anonymous brown globs that come in black and o...  DESPAIR
3596      90272821                           Any full-sized candy bar      JOY
5394      90272821                                        Black Jacks      MEH
7192      90272821                                Bonkers (the candy)  DESPAIR
...            ...                                                ...      ...
176204    90272821                                            Vicodin  DESPAIR
178002    90272821                               Whatchamacallit Bars  DESPAIR
179800    90272821                                        White Bread  DESPAIR
181598    90272821                               Whole Wheat anything  DESPAIR
183396    90272821                            York Peppermint Patties  DESPAIR

[103 rows x 3 columns]

### 11 - clean ` dress` column
>tip : you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [34]:
data['Q10: DRESS'].value_counts(dropna=False)

Q10: DRESS
White and gold    1077
Blue and black     633
Unknown             88
Name: count, dtype: int64

### 12 - clean ` day` column
>tip : you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [35]:
print(data['Q11: DAY'].value_counts(dropna=False))
data['Q11: DAY'] = data['Q11: DAY'].replace('Unknown', data['Q11: DAY'].mode()[0])
data['Q11: DAY'].value_counts(dropna=False)

Q11: DAY
Friday     1089
Sunday      641
Unknown      68
Name: count, dtype: int64

Q11: DAY
Friday    1157
Sunday     641
Name: count, dtype: int64

#  rename columns to it appropriate name

In [36]:
data = data.rename(columns={'Q1: GOING OUT?':"going out", 'Q2: GENDER':"gender", 'Q3: AGE':"age", 'Q4: COUNTRY':"country","Q5: STATE, PROVINCE, COUNTY, ETC" : "area","Q11: DAY":"day","Q10: DRESS":"dress"})
data

,Internal ID,going out,gender,age,country,area,dress,day,"Click Coordinates (x, y)",Media
0,90272821,No,Male,44,United States,NM,White and gold,Sunday,"(84, 25)",Science
1,90272840,No,Male,40,United States,Oregon,White and gold,Sunday,"(75, 23)",Science
2,90272841,No,Male,23,United States,exton pa,White and gold,Friday,"(70, 10)",Science
3,90272852,No,Male,43,Unknown,Unknown,Unknown,Friday,"(75, 23)",Science
4,90272854,No,Male,33,Canada,Ontario,Blue and black,Friday,"(55, 5)",Science
...,...,...,...,...,...,...,...,...,...,...
1795,90314022,No,Female,26,United States,Michigan,White and gold,Friday,"(68, 39)",Science
1796,90314359,No,Male,24,United States,Maryland,White and gold,Friday,Unknown,Unknown
1797,90314580,No,Female,33,United States,New York,Blue and black,Friday,"(70, 26)",Science
1798,90314634,No,Female,26,United States,Tennessee,Blue and black,Friday,"(67, 35)",Science
1799,90314802,No,Female,66,United States,Pennsylvania,White and gold,Sunday,"(19, 26)",Daily Dish

### 13 - check
> after finish cleaning you should make sure your data is clean and that :
- there is no wrong data type
- there is no NaN values
- all the column are cleaing and ready for the next step `EDA`

In [37]:
data.describe()

               age
count  1798.000000
mean     42.918242
std      11.480670
min      10.000000
25%      35.000000
50%      43.000000
75%      50.000000
max      99.000000

In [38]:
print(data.info())
print(candy_data.info())

<class 'pandas.core.frame.DataFrame'>
Index: 1798 entries, 0 to 1799
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Internal ID               1798 non-null   string
 1   going out                 1798 non-null   object
 2   gender                    1798 non-null   object
 3   age                       1798 non-null   int64
 4   country                   1798 non-null   object
 5   area                      1798 non-null   object
 6   dress                     1798 non-null   object
 7   day                       1798 non-null   object
 8   Click Coordinates (x, y)  1798 non-null   object
 9   Media                     1798 non-null   object
dtypes: int64(1), object(8), string(1)
memory usage: 154.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185194 entries, 0 to 185193
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Internal ID  185194 non-null  string
 1   Candy        185194 non-null  object
 2   Rating       185194 non-null  object
dtypes: object(2), string(1)
memory usage: 4.2+ MB
None

In [39]:
print(data.isnull().sum())
print(candy_data.isnull().sum())

Internal ID                 0
going out                   0
gender                      0
age                         0
country                     0
area                        0
dress                       0
day                         0
Click Coordinates (x, y)    0
Media                       0
dtype: int64
Internal ID    0
Candy          0
Rating         0
dtype: int64

### 14 - write a summary about all the cleaning steps

### Summary of Cleaning Steps

**Starting point:** 2,460 rows and 120 columns, with a lot of messiness to sort through.

**1. Media columns**
Combined the four separate media columns into one `Media` column, picking whichever one had a value. Rows with nothing in any of them got labeled "Unknown."

**2. Dropping unnecessary data**
- Removed columns that weren't useful (`Unnamed: 113`, the comments column, the despair-other column) since they were mostly empty
- Dropped rows with too many missing values to be worth keeping
- Converted `Internal ID` to a string, since it's an identifier, not something to do math on

**3. Going Out & Gender**
Filled missing values with the mode for Going Out, and "I'd rather not say" for Gender.

**4. Age**
The messiest column by far. People typed things like "old enough," "60+," "MY NAME JEFF," and "your mom." Steps taken:
- Manually mapped decipherable answers to actual numbers
- Removed entries that were clearly jokes
- Converted the column to numeric
- Filtered out unrealistic ages (under 10 or over 100)
- Filled remaining missing values with the average age

**5. Country**
Same info written a dozen different ways (US, USA, us, America, Murica, etc.). Handled it by:
- Mapping the obvious variants with a dictionary
- Using fuzzy matching against real country names for everything else
- Defaulting to "Unknown" when nothing matched well

**6. State/Province**
Same idea as country — grouped abbreviations and typos into their proper names manually.

**7. Candy ratings (Q6 columns)**
Instead of cleaning each candy column individually, reshaped that whole section into a long-format table (one row per person per candy). Dropped blank ratings, since a missing rating just means the person skipped that candy — not something that needs filling in.

**8. Dress & Day**
Barely needed touching. Day had a few "Unknown" values, replaced with the mode.

**Result:** Main dataset now has correct data types, no leftover garbage values, and no missing data that matters — with candy ratings split into their own table, ready to be joined back in for analysis.

In [40]:
merged = data.merge(candy_data, on='Internal ID', how='left')
merged

,Internal ID,going out,gender,age,country,area,dress,day,"Click Coordinates (x, y)",Media,Candy,Rating
0,90272821,No,Male,44,United States,NM,White and gold,Sunday,"(84, 25)",Science,100 Grand Bar,MEH
1,90272821,No,Male,44,United States,NM,White and gold,Sunday,"(84, 25)",Science,Anonymous brown globs that come in black and o...,DESPAIR
2,90272821,No,Male,44,United States,NM,White and gold,Sunday,"(84, 25)",Science,Any full-sized candy bar,JOY
3,90272821,No,Male,44,United States,NM,White and gold,Sunday,"(84, 25)",Science,Black Jacks,MEH
4,90272821,No,Male,44,United States,NM,White and gold,Sunday,"(84, 25)",Science,Bonkers (the candy),DESPAIR
...,...,...,...,...,...,...,...,...,...,...,...,...
185189,90314802,No,Female,66,United States,Pennsylvania,White and gold,Sunday,"(19, 26)",Daily Dish,Vicodin,JOY
185190,90314802,No,Female,66,United States,Pennsylvania,White and gold,Sunday,"(19, 26)",Daily Dish,Whatchamacallit Bars,DESPAIR
185191,90314802,No,Female,66,United States,Pennsylvania,White and gold,Sunday,"(19, 26)",Daily Dish,White Bread,MEH
185192,90314802,No,Female,66,United States,Pennsylvania,White and gold,Sunday,"(19, 26)",Daily Dish,Whole Wheat anything,DESPAIR
185193,90314802,No,Female,66,United States,Pennsylvania,White and gold,Sunday,"(19, 26)",Daily Dish,York Peppermint Patties,JOY

In [41]:
merged.sample(200)

,Internal ID,going out,gender,age,country,area,dress,day,"Click Coordinates (x, y)",Media,Candy,Rating
132064,90281589,No,Male,38,United States,Texas,White and gold,Friday,"(77, 12)",Science,Coffee Crisp,DESPAIR
85545,90277315,No,Female,31,Canada,Alberta,Unknown,Friday,"(75, 20)",Science,Milky Way,JOY
114600,90279721,No,Female,51,United States,New York,White and gold,Friday,"(82, 34)",Science,Mint Kisses,MEH
85523,90277315,No,Female,31,Canada,Alberta,Unknown,Friday,"(75, 20)",Science,Hershey's Dark Chocolate,JOY
131960,90281588,No,Female,60,United States,Oregon,White and gold,Sunday,"(75, 22)",Science,Chiclets,MEH
...,...,...,...,...,...,...,...,...,...,...,...,...
3645,90272944,No,Male,49,United States,Washington,Blue and black,Sunday,"(70, 10)",Science,Junior Mints,MEH
96258,90278176,No,Male,56,United States,Missouri,Blue and black,Friday,"(83, 41)",Science,Regular M&Ms,JOY
32869,90274048,No,Male,32,United States,New York,Blue and black,Friday,"(74, 34)",Science,Candy that is clearly just the stuff given out...,DESPAIR
105171,90278873,Yes,Male,43,Canada,Ontario,White and gold,Sunday,"(74, 11)",Science,Broken glow stick,DESPAIR
5083,90272991,No,Male,53,United States,Florida,White and gold,Friday,"(71, 15)",Science,Hugs (actual physical hugs),DESPAIR

In [42]:
# Save the cleaned main data
data.to_csv('cleaned_candy_data.csv', index=False)

# Save the candy ratings table
candy_data.to_csv('cleaned_candy_ratings.csv', index=False)

# Or if you merged them into one table
merged.to_csv('cleaned_merged_candy_data.csv', index=False)